/**
 * people.js
 * ---------
 * Everything the chatbot needs to talk about *people* accurately:
 *
 *  - personCard(member):   one uniform contact card (name, role, location,
 *                          credentials, expertise, email, View Profile / Connect)
 *  - answerPersonQuery():  "who is disha", "email of tasnim", "dhisa shah" ...
 *                          (fuzzy name match — typos, first name only, etc.)
 *  - answerSectorExpertsQuery(): "who are the experts in media", "IT/ITES",
 *                          "ngo specialist" ... answered from the specialists
 *                          the website itself lists on each sector page.
 *  - peopleNamedIn(text):  every team member named in a piece of text, so an
 *                          AI-written answer can get real cards under it.
 *
 * All of it is computed from index.json + data/contacts.json in code, so
 * names, roles, locations and emails are exactly what the website shows —
 * nothing here is generated by the LLM.
 */
const fs = require("fs");
const path = require("path");

// Used when the website lists no personal email for someone — clearly labelled
// as the firm's general address in the card, never passed off as theirs.
const GENERAL_EMAIL = "connect@jhsassociates.in";

// ---- small helpers -------------------------------------------------------

// Edit distance where swapping two neighbouring letters counts as ONE typo
// ("dhisa" -> "disha"), which is by far the most common way people mistype.
function distance(a, b) {
  const dp = Array.from({ length: a.length + 1 }, () => Array(b.length + 1).fill(0));
  for (let i = 0; i <= a.length; i++) dp[i][0] = i;
  for (let j = 0; j <= b.length; j++) dp[0][j] = j;
  for (let i = 1; i <= a.length; i++) {
    for (let j = 1; j <= b.length; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      dp[i][j] = Math.min(dp[i - 1][j] + 1, dp[i][j - 1] + 1, dp[i - 1][j - 1] + cost);
      if (i > 1 && j > 1 && a[i - 1] === b[j - 2] && a[i - 2] === b[j - 1]) {
        dp[i][j] = Math.min(dp[i][j], dp[i - 2][j - 2] + 1);
      }
    }
  }
  return dp[a.length][b.length];
}

const norm = (s) => String(s || "").toLowerCase().replace(/[^a-z]/g, "");
const words = (s) => String(s || "").toLowerCase().match(/[a-z]+/g) || [];
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

// How many typos a name-part of this length may have and still count as a match.
function tolerance(len) {
  if (len >= 8) return 2;
  if (len >= 5) return 1;
  return 0;
}
function tokenMatches(q, n) {
  if (q === n) return true;
  if (q.length < 4) return false; // 3-letter words are too easy to match by accident
  if (distance(q, n) <= Math.min(tolerance(n.length), tolerance(q.length))) return true;
  // Same letters scrambled, same first letter ("dhisa" for "disha") — a very
  // common way to mistype a name that a plain edit distance scores as 2 typos.
  return q.length >= 5 && q.length === n.length && q[0] === n[0] && [...q].sort().join("") === [...n].sort().join("");
}
// Looser than tokenMatches (up to 2 typos): only used to rank people who ALREADY
// matched on another part of their name, e.g. "dhisa shah" -> Disha over the
// other five Shahs.
function softMatches(q, n) {
  return q.length >= 4 && n.length >= 4 && distance(q, n) <= 2;
}

// ---- contacts (email / LinkedIn), from data/contacts.json ----------------

function loadContacts() {
  const merged = {};
  for (const file of ["contacts.json", "contacts.overrides.json"]) {
    const p = path.join(__dirname, "..", "data", file);
    if (!fs.existsSync(p)) continue;
    try {
      const data = JSON.parse(fs.readFileSync(p, "utf-8"));
      for (const [name, c] of Object.entries(data)) merged[name] = { ...merged[name], ...c };
    } catch (e) {
      console.warn(`Could not read ${file}:`, e.message);
    }
  }
  return merged;
}

// The same person is often spelled slightly differently across the website
// ("Narayan" / "Narayana" Rao Malla) and one spelling may carry the email while
// another only has the LinkedIn — so merge every entry that is this person,
// closest spelling first, filling in whatever the closer ones are missing.
function contactFor(contacts, name) {
  const target = norm(name);
  const matches = [];
  for (const [key, c] of Object.entries(contacts)) {
    const d = key === name ? 0 : distance(norm(key), target);
    if (d === 0 || (d <= 2 && target.length >= 8)) matches.push({ d, c });
  }
  matches.sort((x, y) => x.d - y.d);
  const merged = {};
  for (const { c } of matches) for (const [k, v] of Object.entries(c)) if (v && !merged[k]) merged[k] = v;
  return merged;
}

// ---- sector topics -------------------------------------------------------

// What visitors actually type for each sector page that lists specialists
// (keys are the exact topic names the crawler stores from those pages).
const TOPIC_ALIASES = {
  Banking: ["banking", "bank", "banks"],
  "Mutual Funds": ["mutual fund", "mutual funds", "amc", "asset management"],
  Broking: ["broking", "broker", "brokers", "brokerage", "stock broking", "stockbroking"],
  "Family-Oriented Businesses": ["family business", "family businesses", "family owned", "family oriented", "family run"],
  Insurance: ["insurance", "insurer", "insurers"],
  "Digital Currency": ["digital currency", "crypto", "cryptocurrency", "bitcoin", "blockchain", "virtual digital asset"],
  NBFC: ["nbfc", "nbfcs", "non banking financial"],
  "Portfolio Management": ["portfolio management", "pms", "portfolio"],
  "Venture Capital": ["venture capital", "vc", "startup", "startups", "start up", "private equity"],
  Housing: ["housing", "housing finance", "hfc"],
  "Gems & Jewellery": ["gems", "gem", "jewellery", "jewelry", "jeweller", "jewellers", "diamond", "diamonds"],
  "Real Estate": ["real estate", "realty", "property", "properties"],
  Retail: ["retail", "retailer", "retailers"],
  "Oil & Gas": ["oil and gas", "oil gas", "oil", "gas", "petroleum"],
  FMCG: ["fmcg", "consumer goods", "fast moving"],
  Commodity: ["commodity", "commodities"],
  Media: ["media", "entertainment", "broadcast", "broadcasting", "ott", "film", "films", "advertising", "publishing"],
  "IT System Audit": ["it system audit", "it systems audit", "it audit system", "system audit", "it audit", "cyber", "cybersecurity", "cyber security", "information security", "infosec"],
  ITeS: ["ites", "it ites", "it enabled services", "it enabled", "bpo", "it services", "software", "saas", "technology"],
  Healthcare: ["healthcare", "health care", "health", "hospital", "hospitals", "pharma", "pharmaceutical", "medical", "clinic", "diagnostics"],
  Construction: ["construction", "infrastructure", "infra", "contractor", "contractors", "builder", "builders"],
  NGO: ["ngo", "ngos", "non profit", "nonprofit", "charity", "charitable"],
  Manufacturing: ["manufacturing", "manufacturer", "manufacturers", "factory", "factories"],
  Logistics: ["logistics", "logistic", "transport", "transportation", "shipping", "supply chain", "freight", "warehouse"],
};

const padded = (text) => ` ${String(text).toLowerCase().replace(/[^a-z0-9]+/g, " ").trim()} `;

// ---- intents -------------------------------------------------------------

const PERSON_INTENT_RE =
  /\b(who|whom|whose|about|tell|details?|info|information|profile|contact|email|e-?mail|mail|connect|reach|linkedin|number|phone|call|speak|talk|meet|know|background|expertise|specialis\w*|works?|based|sits?|located|qualification|qualified)\b/i;
const EMAIL_INTENT_RE = /\b(e-?mail|mail|contact|reach)\b/i;
const EXPERT_INTENT_RE =
  /\b(expert|experts|expertise|specialist|specialists|specialise|specialize|specialising|specializing|who|whom|partner|partners|consultant|consultants|advisor|advisors|adviser|advisers|professional|professionals|handle|handles|handling|head|lead|leads|contact|reach|speak|talk|person|people|team|resource|resources)\b/i;
const CONTENT_INTENT_RE = /\b(article|articles|blog|blogs|white\s?papers?|case\s?stud\w*|podcasts?|newsletters?|regulatory|circulars?)\b/i;
// Name parts that are also ordinary words — a lone match on one of these
// ("tell me MORE about ...") must not be read as a person.
const COMMON_NAME_TOKENS = new Set(["more", "rao"]);

// ---- factory -------------------------------------------------------------

function createPeople({ getIndex, findLocationInQuestion }) {
  let contacts = loadContacts();
  // Pick up edits to contacts.json without a restart (unref: never keeps the process alive).
  fs.watchFile(path.join(__dirname, "..", "data", "contacts.json"), { interval: 60000, persistent: false }, () => {
    contacts = loadContacts();
  });

  const team = () => getIndex().filter((i) => i.source === "team");
  const teamByName = (name) => team().find((m) => m.name === name) || team().find((m) => norm(m.name) === norm(name));

  const shortDesc = (m) => m.text.split(". ").slice(1).join(". ").replace(/\s*Specialisations:.*$/, "").trim();
  const specialisationsOf = (m) => ((m.text.match(/Specialisations:\s*(.+?)\.?\s*$/) || [])[1] || "").trim();

  // The one card shape every answer uses.
  function personCard(m) {
    const c = contactFor(contacts, m.name);
    const email = c.email || GENERAL_EMAIL;
    const linkedin = c.linkedin || (/linkedin\.com/i.test(m.linkedin || "") ? m.linkedin : null);
    const subject = encodeURIComponent(`Enquiry for ${m.name}`);
    return {
      name: m.name,
      role: m.role || "",
      location: m.location || "",
      creds: m.creds || "",
      expertise: shortDesc(m),
      specialisations: specialisationsOf(m),
      email,
      emailIsGeneral: !c.email,
      actions: [
        { label: "View Profile", url: linkedin || m.url },
        { label: "Connect", url: `mailto:${email}?subject=${subject}` },
      ],
    };
  }

  // A list item: `person` for card-aware clients, `text`+`link` as the plain
  // fallback for anything older.
  function personItem(m, position) {
    const card = personCard(m);
    const prefix = position ? `${position}. ` : "";
    return {
      text: `${prefix}**${m.name}** — ${m.location}, ${m.role}. ${card.expertise}`.trim(),
      link: card.actions[0],
      person: card,
    };
  }

  // ---- "who is <name>" ---------------------------------------------------
  function answerPersonQuery(message) {
    const qTokens = words(message).filter((w) => w.length >= 2);
    if (!qTokens.length || /\bhow many\b/i.test(message)) return null;

    const scored = [];
    for (const m of team()) {
      const nameTokens = words(m.name).filter((t) => t.length >= 2);
      const matchedQ = new Set();
      let score = 0;
      let onlyCommon = true;
      for (const nt of nameTokens) {
        const q = qTokens.find((t) => tokenMatches(t, nt));
        if (q) {
          score++;
          matchedQ.add(q);
          if (!COMMON_NAME_TOKENS.has(nt)) onlyCommon = false;
        }
      }
      if (score > 0 && (score >= 2 || !onlyCommon)) {
        // Tie-break: a leftover word in the question that is nearly one of this
        // person's other name parts counts as half a match.
        const spare = qTokens.filter((t) => !matchedQ.has(t) && t.length >= 4);
        const soft = nameTokens.filter((nt) => !qTokens.some((t) => tokenMatches(t, nt)) && spare.some((t) => softMatches(t, nt))).length;
        scored.push({ m, score: score + soft * 0.5, matched: [...matchedQ] });
      }
    }
    if (!scored.length) return null;

    const best = Math.max(...scored.map((s) => s.score));
    const top = scored.filter((s) => s.score === best);

    // Only treat it as a people question when it reads like one — a full name
    // is enough on its own; a bare first/last name needs a "who is / about /
    // email ..." style cue or a very short message.
    const looksLikePerson = best >= 2 || PERSON_INTENT_RE.test(message) || qTokens.length <= 4;
    if (!looksLikePerson) return null;

    const members = top.map((s) => s.m).slice(0, 8);
    let intro;
    if (members.length === 1) {
      intro = EMAIL_INTENT_RE.test(message)
        ? `Here's how to reach **${members[0].name}**:`
        : `Here are the details for **${members[0].name}**:`;
    } else {
      const said = top[0].matched.join(" ");
      intro = `I found ${members.length} people matching "${said}" — tell me which one you mean, or use their details below:`;
    }
    return { intro, items: members.map((m) => personItem(m)), links: [] };
  }

  // Every word the website itself uses (services, articles, pages). A word that
  // really appears there is never treated as a typo of something else —
  // "assurance" is a service of ours, not a misspelling of "insurance".
  let siteWordsCache = null;
  let siteWordsFor = -1;
  function siteWords() {
    const idx = getIndex();
    if (siteWordsCache && siteWordsFor === idx.length) return siteWordsCache;
    const set = new Set();
    for (const item of idx) {
      if (item.source === "team" || item.source === "sector-specialist") continue;
      for (const w of (item.text || "").toLowerCase().match(/[a-z]{5,}/g) || []) set.add(w);
    }
    siteWordsCache = set;
    siteWordsFor = idx.length;
    return set;
  }

  // ---- "who are the experts in <sector>" ----------------------------------
  function findTopics(message, availableTopics) {
    const text = padded(message);
    const found = new Map(); // topic -> the longest alias that matched
    for (const topic of availableTopics) {
      const aliases = [topic.toLowerCase(), ...(TOPIC_ALIASES[topic] || [])];
      for (const alias of aliases) {
        if (text.includes(padded(alias)) && alias.length > (found.get(topic) || "").length) found.set(topic, alias);
      }
    }
    if (found.size) return dropShadowed(found);

    // Nothing matched exactly — forgive one typo in a single word ("helthcare").
    const known = siteWords();
    const qTokens = words(message).filter((w) => w.length >= 5 && !known.has(w));
    for (const topic of availableTopics) {
      const singles = [topic.toLowerCase(), ...(TOPIC_ALIASES[topic] || [])].filter((a) => /^[a-z]{5,}$/.test(a));
      for (const alias of singles) {
        if (qTokens.some((t) => t !== alias && distance(t, alias) <= 1)) {
          if (alias.length > (found.get(topic) || "").length) found.set(topic, alias);
        }
      }
    }
    return dropShadowed(found);
  }
  // "non banking financial" (NBFC) also contains "banking" (Banking) — when one
  // topic's matched phrase sits inside a longer phrase matched for another
  // topic, only the longer, more specific one is meant.
  function dropShadowed(found) {
    const entries = [...found.entries()];
    return entries
      .filter(([topic, alias]) => !entries.some(([other, o]) => other !== topic && o.length > alias.length && padded(o).includes(padded(alias))))
      .map(([topic]) => topic);
  }

  function answerSectorExpertsQuery(message) {
    if (!EXPERT_INTENT_RE.test(message) || CONTENT_INTENT_RE.test(message)) return null;

    const specialists = getIndex().filter((i) => i.source === "sector-specialist");
    if (!specialists.length) return null;
    const topics = [...new Set(specialists.map((s) => s.topic))];
    const matched = findTopics(message, topics);
    if (!matched.length) return null;

    const location = findLocationInQuestion ? findLocationInQuestion(message) : null;
    const pageFor = (topic) => specialists.find((s) => s.topic === topic).pageUrl;

    const items = [];
    const links = [];
    let total = 0;
    for (const topic of matched) {
      let members = [];
      const seen = new Set();
      for (const s of specialists.filter((x) => x.topic === topic)) {
        if (seen.has(s.name)) continue;
        seen.add(s.name);
        members.push(teamByName(s.name) || s);
      }
      let note = "";
      if (location) {
        const inCity = members.filter((m) => location.cities.includes(m.location));
        if (inCity.length) members = inCity;
        else note = ` (none based in ${location.label}, so here is everyone)`;
      }
      total += members.length;
      if (matched.length > 1) {
        items.push({ text: `**${topic}** — ${members.length} specialist${members.length === 1 ? "" : "s"}${note}:` });
      }
      members.forEach((m) => items.push(personItem(m)));
      links.push({ url: pageFor(topic), label: `View ${topic} page` });
    }

    const intro =
      matched.length === 1
        ? `For **${matched[0]}**, we have ${total} specialist${total === 1 ? "" : "s"}${location ? ` (${location.label})` : ""}:`
        : `Here are our specialists for ${matched.map((t) => `**${t}**`).join(" and ")}:`;
    return { intro, items, links };
  }

  // ---- people named in an AI-written answer ------------------------------
  function peopleNamedIn(text) {
    const hits = [];
    for (const m of team()) {
      const re = new RegExp(`\\b${escapeRe(m.name)}\\b`, "i");
      const at = text.search(re);
      if (at >= 0) hits.push({ m, at });
    }
    return hits.sort((a, b) => a.at - b.at).map((h) => h.m);
  }

  return { personCard, personItem, answerPersonQuery, answerSectorExpertsQuery, peopleNamedIn, teamByName, GENERAL_EMAIL };
}

module.exports = { createPeople, GENERAL_EMAIL };
