import LegalPage from './LegalPage'
import type { LegalBlock } from './LegalPage'

const blocks: LegalBlock[] = [
  { type: 'h2', text: 'Interpretation and Definitions' },
  { type: 'h3', text: 'Interpretation' },
  {
    type: 'p',
    text: 'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
  },
  { type: 'h3', text: 'Definitions' },
  { type: 'p', text: 'For the purposes of this Privacy Policy:' },
  {
    type: 'dl',
    items: [
      { term: 'Account', desc: 'means a unique account created for You to access our Service or parts of our Service.' },
      { term: 'Affiliate', desc: 'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.' },
      { term: 'Company ("the Company", "We", "Us" or "Our")', desc: 'refers to JHS & Associates LLP, B Wing, 4th floor, Navkar Chambers, Marol Naka Metro Station, Andheri (East), Mumbai – 400059.' },
      { term: 'Cookies', desc: 'are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.' },
      { term: 'Country', desc: 'refers to: Maharashtra, India.' },
      { term: 'Device', desc: 'means any device that can access the Service such as a computer, a cellphone or a digital tablet.' },
      { term: 'Personal Data', desc: 'is any information that relates to an identified or identifiable individual.' },
      { term: 'Service', desc: 'refers to the Website.' },
      { term: 'Service Provider', desc: 'means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.' },
      { term: 'Usage Data', desc: 'refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).' },
      { term: 'Website', desc: 'refers to JHS Associates, accessible from www.jhsassociates.in.' },
      { term: 'You', desc: 'means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.' },
    ],
  },

  { type: 'h2', text: 'Collecting and Using Your Personal Data' },
  { type: 'h3', text: 'Types of Data Collected' },
  { type: 'h3', text: 'Personal Data' },
  {
    type: 'p',
    text: 'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:',
  },
  {
    type: 'ul',
    items: ['Email address', 'First name and last name', 'Phone number', 'Address, State, Province, ZIP/Postal code, City'],
  },

  { type: 'h3', text: 'Usage Data' },
  { type: 'p', text: 'Usage Data is collected automatically when using the Service.' },
  {
    type: 'p',
    text: "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
  },
  {
    type: 'p',
    text: 'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.',
  },
  {
    type: 'p',
    text: 'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.',
  },

  { type: 'h3', text: 'Tracking Technologies and Cookies' },
  {
    type: 'p',
    text: 'We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:',
  },
  {
    type: 'ul',
    items: [
      'Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.',
      'Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.',
    ],
  },
  {
    type: 'p',
    text: 'Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. We use both Session and Persistent Cookies for the purposes set out below:',
  },
  {
    type: 'dl',
    items: [
      { term: 'Necessary / Essential Cookies (Session · administered by Us)', desc: 'These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help authenticate users and prevent fraudulent use of user accounts.' },
      { term: 'Cookies Policy / Notice Acceptance Cookies (Persistent · administered by Us)', desc: 'These Cookies identify if users have accepted the use of cookies on the Website.' },
      { term: 'Functionality Cookies (Persistent · administered by Us)', desc: 'These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference, to provide You with a more personal experience.' },
    ],
  },

  { type: 'h3', text: 'Use of Your Personal Data' },
  { type: 'p', text: 'The Company may use Personal Data for the following purposes:' },
  {
    type: 'ul',
    items: [
      'To provide and maintain our Service, including to monitor the usage of our Service.',
      'To manage Your Account: to manage Your registration as a user of the Service.',
      'For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.',
      "To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.",
      'To provide You with news, special offers and general information about other goods, services and events which we offer, unless You have opted not to receive such information.',
      'To manage Your requests: To attend and manage Your requests to Us.',
      'For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.',
      'For other purposes: such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.',
    ],
  },
  { type: 'p', text: 'We may share Your personal information in the following situations:' },
  {
    type: 'ul',
    items: [
      'With Service Providers: to monitor and analyze the use of our Service, and to contact You.',
      'For business transfers: in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.',
      'With Affiliates: in which case we will require those affiliates to honor this Privacy Policy.',
      'With business partners: to offer You certain products, services or promotions.',
      'With other users: when You share personal information or otherwise interact in public areas with other users.',
      'With Your consent: for any other purpose with Your consent.',
    ],
  },

  { type: 'h2', text: 'Retention of Your Personal Data' },
  {
    type: 'p',
    text: 'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.',
  },
  {
    type: 'p',
    text: 'The Company will also retain Usage Data for internal analysis purposes, generally for a shorter period, except when this data is used to strengthen security, improve functionality, or We are legally obligated to retain it for longer periods.',
  },

  { type: 'h2', text: 'Transfer of Your Personal Data' },
  {
    type: 'p',
    text: "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. This information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where data protection laws may differ from those in Your jurisdiction.",
  },
  { type: 'p', text: 'Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.' },
  {
    type: 'p',
    text: 'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy, and no transfer of Your Personal Data will take place to an organization or a country unless adequate controls are in place.',
  },

  { type: 'h2', text: 'Delete Your Personal Data' },
  { type: 'p', text: 'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.' },
  { type: 'p', text: 'Our Service may give You the ability to delete certain information about You from within the Service.' },
  {
    type: 'p',
    text: 'You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.',
  },
  { type: 'p', text: 'Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.' },

  { type: 'h2', text: 'Disclosure of Your Personal Data' },
  { type: 'h3', text: 'Business Transactions' },
  {
    type: 'p',
    text: 'If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.',
  },
  { type: 'h3', text: 'Law Enforcement' },
  {
    type: 'p',
    text: 'Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.',
  },
  { type: 'h3', text: 'Other Legal Requirements' },
  { type: 'p', text: 'The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:' },
  {
    type: 'ul',
    items: [
      'Comply with a legal obligation',
      'Protect and defend the rights or property of the Company',
      'Prevent or investigate possible wrongdoing in connection with the Service',
      'Protect the personal safety of Users of the Service or the public',
      'Protect against legal liability',
    ],
  },

  { type: 'h2', text: 'Security of Your Personal Data' },
  {
    type: 'p',
    text: 'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.',
  },

  { type: 'h2', text: "Children's Privacy" },
  {
    type: 'p',
    text: 'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.',
  },
  {
    type: 'p',
    text: "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.",
  },

  { type: 'h2', text: 'Links to Other Websites' },
  {
    type: 'p',
    text: "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.",
  },
  { type: 'p', text: 'We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.' },

  { type: 'h2', text: 'Changes to this Privacy Policy' },
  { type: 'p', text: 'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.' },
  {
    type: 'p',
    text: 'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective, and update the "Last updated" date at the top of this Privacy Policy.',
  },
  { type: 'p', text: 'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.' },
]

export default function PrivacyPolicy() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      lastUpdated="January 27, 2025"
      intro="This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy."
      blocks={blocks}
    />
  )
}
